language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t 239002210/react-complex -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true 239002210/react-complex npm test
